import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/page";
import Footer from "./components/footer/page";
import "@fortawesome/fontawesome-free/css/all.min.css";
// import { styleText } from "util";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Index Default page ",
  description: "Generated by Hamza Shabir",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
